version: "3"
services:
  mysqlspringboot-dockervolume:
    container_name: mysqlspringboot-dockervolume
    image: mysqlspringboot-dockervolume
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306


  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/madhura/Desktop/db:/var/lib/mysql

    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root





