azure:
  keyvault:
      enabled: true
      uri: https://firstkeyvaultmadhu.vault.azure.net/
      client-id: clientId
      client-key: clientSecret
      tenant-id: c752025tenntId
      token-acquire-timeout-seconds: 60
      refresh-interval: 1800000
  servicebus:
      connection-string: ${spring-queue}
      mqueue: todayqueue



spring:
  jms:
    servicebus:
      connection-string: ${spring-queue}
      idle-timeout: 1800000
      pricing-tier: Standard


madhura:
  queue: todayqueue

