apiVersion: v1
kind: Service
metadata:
  name: kubsql
spec:
  ports:
  - port: 3306
  selector:
    app: kubsql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubsql
spec:
  selector:
    matchLabels:
      app: kubsql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubsql
    spec:
      containers:
      - image: politieanswaste.azurecr.io/customsql:latest
        name: kubsql
        ports:
        - containerPort: 3306
          name: kubsql        